create table brand (
    use_yn char(1) not null,
    brand_id bigint generated by default as identity,
    brand_name varchar(30) not null,
    primary key (brand_id)
);

create table product (
        category varchar(20) not null,
        brand_id bigint not null,
        price bigint not null,
        product_id bigint generated by default as identity,
        product_name varchar(50) not null,
        primary key (product_id)
);
